### ISSUE TITLE
I am uable to install the required version of tensorflow-gpu and get an error when trying to run on the latest version. 

### ISSUE THREAD

**Issue by LivelyCarpet87** [drewszurko/tensorflow-2-style-transfer#1]
The following is the output when I try to run the program. Pointers on how to fix this will be much appreciated. 

/home/livelycarpet87/.local/lib/python3.8/site-packages/absl/flags/_validators.py:356: UserWarning: Flag --content_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/livelycarpet87/.local/lib/python3.8/site-packages/absl/flags/_validators.py:356: UserWarning: Flag --style_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
2020-06-30 00:47:34.045317: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-30 00:47:34.106372: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-06-30 00:47:34.106413: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: livelycarpet87-desktop
2020-06-30 00:47:34.106422: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: livelycarpet87-desktop
2020-06-30 00:47:34.106499: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.36.6
2020-06-30 00:47:34.106529: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.100.0
2020-06-30 00:47:34.106536: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 440.100.0 does not match DSO version 450.36.6 -- cannot find working devices in this configuration
2020-06-30 00:47:34.106879: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-30 00:47:34.113404: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3600070000 Hz
2020-06-30 00:47:34.113761: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fdccc000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-30 00:47:34.113782: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    app.run(main)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/livelycarpet87/.local/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 60, in main
    mdl = models.StyleContent(content_img, style_img)
  File "/home/livelycarpet87/tensorflow-2-style-transfer/models.py", line 54, in __init__
    self.vgg = get_vgg_layers(self.STYLE_LAYERS + self.CONTENT_LAYERS)
  File "/home/livelycarpet87/tensorflow-2-style-transfer/ops.py", line 38, in get_vgg_layers
    vgg = applications.VGG19(include_top=False, weights='imagenet')
AttributeError: module 'tensorflow.python.keras.applications' has no attribute 'VGG19'

**Comment by jaretburkett** [comment]
replace 

```python
from tensorflow.python.keras import applications
from tensorflow.python.keras import models
```
with
```python
from tensorflow.keras import applications
from tensorflow.keras import models
```

in `ops.py`
